org.gradle.jvmargs=-Xmx1800m -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-arm64
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/usr/lib/jvm/java-17-openjdk-arm64
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.parallel=false
org.gradle.caching=true
kotlin.incremental=true
